default.icon = /resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
Folder.characters=/resources/assets/sprites/characters
user.name=Hero
user.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
icon1=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
icon2=/resources/assets/sprites/characters/Fatecando-M_HAPPY-icon.png