#
#Thu Oct 30 00:13:18 GMT-03:00 2025
Folder.characters=/resources/assets/sprites/characters
default.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
default.name=Hero
icon1=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
icon2=/resources/assets/sprites/characters/Fatecando-M_HAPPY-icon.png
user.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
user.name=asd
