#
#Tue Oct 28 05:33:40 GMT-03:00 2025
Folder.characters=/resources/assets/sprites/characters
default.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
icon1=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
icon2=/resources/assets/sprites/characters/Fatecando-M_HAPPY-icon.png
user.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
user.name=Hero
