#
#Wed Oct 29 18:05:52 BRT 2025
default.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
default.name=Hero
user.icon=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
user.name=Hero
Folder.characters=/resources/assets/sprites/characters
icon1=/resources/assets/sprites/characters/Fatecando-F_HAPPY-icon.png
icon2=/resources/assets/sprites/characters/Fatecando-M_HAPPY-icon.png
