/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author dti
 */
public class TelaTorreHanoi extends javax.swing.JPanel {

    /**
     * Creates new form TelaTorreHanoii
     */
    public TelaTorreHanoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        torrePanel2 = new javax.swing.JPanel();
        disc1 = new javax.swing.JLabel();
        disc2 = new javax.swing.JLabel();
        disc3 = new javax.swing.JLabel();
        disc4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        torrePanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        torrePanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(25, 26, 31));

        jPanel2.setBackground(new java.awt.Color(25, 26, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        torrePanel2.setBackground(new java.awt.Color(102, 255, 255));
        torrePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        torrePanel2.setOpaque(false);
        torrePanel2.setLayout(new javax.swing.BoxLayout(torrePanel2, javax.swing.BoxLayout.Y_AXIS));

        disc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/Discs/SMALL-PINK.png"))); // NOI18N
        disc1.setAlignmentX(0.5F);
        torrePanel2.add(disc1);

        disc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/Discs/MEDIUM-GREEN.png"))); // NOI18N
        disc2.setAlignmentX(0.5F);
        torrePanel2.add(disc2);

        disc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/Discs/BIG-RED.png"))); // NOI18N
        disc3.setAlignmentX(0.5F);
        torrePanel2.add(disc3);

        disc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/Discs/GIANT-PURPLE.png"))); // NOI18N
        disc4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        disc4.setAlignmentX(0.5F);
        torrePanel2.add(disc4);

        jPanel2.add(torrePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 150, 330, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/UI/torre.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/UI/torre.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jPanel5.setBackground(new java.awt.Color(25, 26, 31));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(102, 255, 255));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        torrePanel3.setBackground(new java.awt.Color(102, 255, 255));
        torrePanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        torrePanel3.setOpaque(false);
        torrePanel3.setLayout(new javax.swing.BoxLayout(torrePanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(torrePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 320, 240));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/UI/torre.png"))); // NOI18N
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jPanel9.setBackground(new java.awt.Color(25, 26, 31));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        torrePanel1.setBackground(new java.awt.Color(102, 255, 255));
        torrePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        torrePanel1.setOpaque(false);
        torrePanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                torrePanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        torrePanel1.setLayout(new javax.swing.BoxLayout(torrePanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel9.add(torrePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 320, 240));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/sprites/UI/torre.png"))); // NOI18N
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void torrePanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_torrePanel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_torrePanel1AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disc1;
    private javax.swing.JLabel disc2;
    private javax.swing.JLabel disc3;
    private javax.swing.JLabel disc4;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel torrePanel1;
    private javax.swing.JPanel torrePanel2;
    private javax.swing.JPanel torrePanel3;
    // End of variables declaration//GEN-END:variables
}
